// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"
)

type Entry struct {
	ID       int64 `json:"id"`
	WalletID int64 `json:"wallet_id"`
	// can be negative or positive
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}

type Transfer struct {
	ID         int64 `json:"id"`
	FromWallet int64 `json:"from_wallet"`
	ToWallet   int64 `json:"to_wallet"`
	// must be positive
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}

type Wallet struct {
	ID        int64     `json:"id"`
	Type      string    `json:"type"`
	FullName  string    `json:"full_name"`
	Document  string    `json:"document"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	Balance   int64     `json:"balance"`
	CreatedAt time.Time `json:"created_at"`
}
